name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        # --force is only for jest version 30.0.0-alpha.5 to work with react testing library.
        # Only used for next frame testing, so it won't cause any issues.
        run: npm install --force

      - name: Run all tests
        run: npm test
